# Copyright (c) 2017, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: java

services:
  - docker

install:
  - mvn -N io.takari:maven:0.7.7:wrapper

jobs:
  include:
    - stage: "win-build"
      name: "Windows Build"
      os: windows
      language: bash
      install:
        - choco install jdk8 -params 'installdir=c:\\java8'
        - export JAVA_HOME="c:\\java8"\\
        - export PATH="$PATH;$JAVA_HOME\\bin"
      script:
        - cmd.exe .\mvnw.cmd install -B -V
    - stage: "linux-build"
      name:  "Linux Build"
      os: linux
      language: java
      jdk: openjdk8
      script:
        - mvn install -B -V

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mvn clean install; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then powershell .\mvnw.cmd clean install; f

cache:
  directories:
  - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)
